doc: fix missing include
This fixes the following error.

-----
  CXX      examples/calc++/examples_calc___calc__-calc++-scanner.o
examples/calc++/calc++-scanner.ll: In member function 'void calcxx_driver::scan_begin()':
examples/calc++/calc++-scanner.ll:68:59: error: 'strerror' was not declared in this scope
       error ("cannot open " + file + ": " + strerror(errno));
                                                           ^
-----

    modified:   doc/bison.texi